// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TabletobClubBot;

#nullable disable

namespace TabletobClubBot.Migrations
{
    [DbContext(typeof(TCDBContext))]
    [Migration("20260728201205_RenameHqConfigs")]
    partial class RenameHqConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TabletobClubBot.Models.Config.HQChannel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("BotOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer");

                    b.Property<int?>("HQConfigID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("HQConfigID");

                    b.ToTable("HQChannel");
                });

            modelBuilder.Entity("TabletobClubBot.Models.Config.HQConfig", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("hqConfigs");
                });

            modelBuilder.Entity("TabletobClubBot.Models.Config.HQChannel", b =>
                {
                    b.HasOne("TabletobClubBot.Models.Config.HQConfig", null)
                        .WithMany("Channels")
                        .HasForeignKey("HQConfigID");
                });

            modelBuilder.Entity("TabletobClubBot.Models.Config.HQConfig", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
